- hosts: localhost
  tasks:
  - name: install Git
    yum: name=git state=latest
    become: yes
    become_method: sudo      
  - name: clone myrepo
    git: repo=https://github.com/shimib/myrepo.git dest=~/repo
  - name: clone petclinic
    git: repo=https://github.com/shimib/spring-petclinic.git dest=~/petclinic
